#CREATE DATABASE user;

#USE user;

/*
CREATE TABLE IF NOT EXISTS users (
 id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
 username VARCHAR(128) NOT NULL,
 email VARCHAR(100) NOT NULL,
 password VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
*/

